spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.25.129/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.25.129
    port: 6379

server:
  context-path: /sell



wechat:
  mpAppId: wxa6a469787cc9a17d
  mpAppSecret: 9c133247be68775f072cb1631d05ce49

projectUrl:
  sell: http://mathilda.s1.natapp.cc